package com.qau.model;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.ID
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.TYPE
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.NAME
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.ID
     *
     * @return the value of TAG.ID
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.ID
     *
     * @param id the value for TAG.ID
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.TYPE
     *
     * @return the value of TAG.TYPE
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.TYPE
     *
     * @param type the value for TAG.TYPE
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.NAME
     *
     * @return the value of TAG.NAME
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.NAME
     *
     * @param name the value for TAG.NAME
     *
     * @mbg.generated Sun Mar 15 11:16:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}